# Generated by Django 3.0.8 on 2020-08-07 01:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(max_length=1000, verbose_name='내용')),
                ('writer', models.CharField(max_length=30, verbose_name='작성자')),
                ('write_date', models.DateTimeField(default=datetime.datetime(2020, 8, 7, 10, 2, 12, 783495), verbose_name='작성일자')),
                ('click_num', models.IntegerField(default=0, verbose_name='조회수')),
                ('like_num', models.IntegerField(default=0, verbose_name='좋아요')),
                ('unlike_num', models.IntegerField(default=0, verbose_name='싫어요')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='아이디')),
                ('password', models.CharField(max_length=30, verbose_name='패스워드')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100, verbose_name='댓글')),
                ('writer', models.CharField(max_length=30, verbose_name='작성자')),
                ('write_date', models.DateTimeField(default=datetime.datetime(2020, 8, 7, 10, 2, 12, 783495), verbose_name='작성일자')),
                ('like_num', models.IntegerField(default=0, verbose_name='좋아요')),
                ('unlike_num', models.IntegerField(default=0, verbose_name='싫어요')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Article')),
            ],
        ),
    ]
