# Generated by Django 3.0.8 on 2020-08-04 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='아이디')),
                ('password', models.CharField(max_length=30, verbose_name='패스워드')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='write_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 4, 15, 34, 59, 642363), verbose_name='작성일자'),
        ),
    ]
