# Generated by Django 3.0.8 on 2020-08-07 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='write_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 11, 11, 24, 985960), verbose_name='작성일자'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=200, verbose_name='댓글'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='write_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 11, 11, 24, 985960), verbose_name='작성일자'),
        ),
    ]
